title: SkyBolt
url: "https://agent.skylershuman.com"
baseurl: ""
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
sass:
  style: compressed
defaults:
  - scope:
      path: ""
    values:
      layout: default
